### ISSUE TITLE
for 1.8 we need to make the following changes 

### ISSUE THREAD

**Issue by sathish4fri** [Centillien/videos#1]
add_to_river('river/object/videos/create', 'create',elgg_get_logged_in_user_guid(), $video->guid);
instead of 

elgg_create_river_item(array(
'view' => 'river/object/videos/create',
'action_type' => 'create',
'subject_guid' => elgg_get_logged_in_user_guid(),
'object_guid' => $video->guid,
));

in action page (save.php) line 59 change with above code ..

**Comment by gerard-kanters** [comment]
Thanks, this should fix it.
