### ISSUE TITLE
Fatal error with the wire disabled in 1.9 

### ISSUE THREAD

**Issue by insideth** [Centillien/videos#2]
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function thewire_filter() in /home/www/redup_triploader_com/htdocs/mod/videos/views/default/river/object/thewire/create.php on line 20" while reading response header from upstream

**Comment by gerard-kanters** [comment]
Do you have the wire plugin disabled ? This function that you are stumbling upon is part of that plugin. 

I will mandate the use of that plugin.
