### ISSUE TITLE
The videos plugins and some features do not work properly

### ISSUE THREAD

**Issue by olairmarcos** [Centillien/videos#7]
Hello, I installed the video plugins and some features do not work properly.
  - In full page video does not open big, the video appears each small (284px)
  - I use the elgg plugin site-wide categories. When saved the video it is saved in the chosen category. In video list, when I click on the category, it asks me an error message.
Thank you for this wonderful plugin.
Thank you for your help.
Elgg version 1.9.0
Videos version 1.10.4

**Comment by gerard-kanters** [comment]
On what device are you testing, if it is shown small then the plugin has detected a mobile device. If you use other plugins that also (try to) detect mobile devices, put the videos plugin below that one so detection will be done by the videos plugin. 

The issue with site-wide categories is probably related to that plugin.
